# Generated by Django 3.2.3 on 2021-06-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CortMapApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
